public class dataTypesDemo {
    public void displaydataTypesDemo() {
        String name = 'Rachel';
        Integer seasons = 10;
        Boolean Favorite = TRUE;

        System.debug('Favorite Friends Character is '+name);
        System.debug('Friends has how many season? '+seasons);
        System.debug('Is Joey cute? '+Favorite);

    }

    public void testCalculator(){
        calculator calc = new calculator();
        calc.add(5,6);
    }
}