
UserNestedJSONCallout.NestedJSONCallout();

SOAPService.numberCoversionSOAPCall();
SOAPService.calculatorServicesCall();
SOAPService.CountryInfoServicesCall();


AnimalsCallout.fetchAnimals1();
AnimalsCallout.fetchAnimals2();

UserContactRecordCreateCallout.getUsers();

UserBasicAuthenticationCallout.getUsersAuthenticate();

UserBasicAuthenticationCallout.getUsersNamedCredential();

UsersPOSTCallout.createUsersPOST();

CovidCalloutUS.getUSCovidInfo();